const variables = {
  colorWhite: "#ffffff",
  colorBlack: "#000000",
  colorGrayDarkest: "#222222",
  colorGrayDark: "#343a40",
  colorGray: "#6c757d",
  colorGrayMedium: "#666666",
  colorGrayMediumLight: "#aaaaaa",
  colorGrayCustom: "#4a5568",
  colorGrayLight: "#eaeaea",
  colorGrayLightest: "#f8f9fa",
  colorBlueMain: "#007bff",
  colorBlueLight: "#17a2b8",
  colorLightBlueDark: "#c0e8e5",
  colorLightBlueMain: "#cef6f3",
  colorLightBlueLight: "#deffff",
  colorGoldMain: "#c8ac80",
  colorGoldDark: "#b68a45",
  colorGoldLight: "#f3eadf",
  colorYellowLight: "#fff7e6",
  colorOrange: "#d77b00",
  colorGreenDark: "#006400",
  colorGreenMain: "#28a745",
  colorGreenLight: "#90ee90",
  colorGreenSoft: "#d4edda",
  colorRedDark: "#852221",
  colorRedLight: "#f9dedc",
  colorSuccess: "#28a745",
  colorError: "#dc3545",
  colorWarning: "#ffc107",
  colorInfo: "#17a2b8",
  colorPrimary: "#b68a45",
  colorSecondary: "#c8ac80",
  colorTextPrimary: "#222222",
  colorTextSecondary: "#343a40",
  colorTextInverted: "#ffffff",
  colorBackgroundPrimary: "#ffffff",
  colorBackgroundSecondary: "#f7f5f2",
  colorBorderDefault: "#eaeaea",
  fontFamilyBase: '"Poppins", sans-serif',
  fontFamilyHeadings: '"Fira Code", monospace',
  fontFamilyMonospace: '"Fira Code", monospace',
};

export default variables;
